# List the start up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
# runs during prebuild => https://www.gitpod.io/docs/configure/projects/prebuilds
tasks:
  - name: Script Task
    init: |
      echo "start Init"
      sudo apt install gh 
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install
      export AWS_CLI_AUTO_PROMPT=on
     
    command: echo 'start script'

# List the ports to expose. Learn more: https://www.gitpod.io/docs/configure/workspaces/ports
ports:
  - name: Frontend
    description: Port 3000 for the frontend
    port: 3000
    onOpen: open-preview

# Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart
